### ISSUE TITLE
EndsWithTest.java:40-42: Ban all overloads of the former...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#80]
The puzzle `52-f2eb48e2` from #52 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/cb29b6c72f31e95062117ed42a52b201f9898047/src/test/java/org/llorllale/cactoos/matchers/EndsWithTest.java#L40-L42

The puzzle was created by @dgroup on 15-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #52.

**Comment by 0crat** [comment]
Job [#80](https://github.com/llorllale/cactoos-matchers/issues/80) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#80](https://github.com/llorllale/cactoos-matchers/issues/80) assigned to @borysfan[/z](https://www.0crat.com/u/borysfan), here is [why](https://www.0crat.com/footprint/C63314D6Z/c79588aa-ad98-49b4-b684-2ec8ef90d50d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by borysfan** [comment]
I went through the code and it seems that job #80 is already solved. No work is needed there.

**Comment by 0pdd** [comment]
The puzzle `52-f2eb48e2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#99](https://github.com/llorllale/cactoos-matchers/issues/99) is still not solved.

**Comment by 0crat** [comment]
The job [#80](https://github.com/llorllale/cactoos-matchers/issues/80) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @borysfan[/z](https://www.0crat.com/u/borysfan)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#99](https://github.com/llorllale/cactoos-matchers/issues/99) is solved here.
